### ISSUE TITLE
UI breaks intermittently 

### ISSUE THREAD

**Issue by 5-c-o** [mythicrp/mythic_notify#2]
I'm having an issue with my UI after converting notifications to mythic.

Menu text and draw text will randomly disappear (eg. doorlocks, ID's over head, street names, outlaw notifications are blank.)

Existing ESX notifications seem to get mixed up at the same time (eg. Salary notification will say you got paid, then will insert a value from a different notification.)

When this happens, there are no errors in either the client or server consoles, so it's been very difficult to pinpoint however no other changes were made to the server when this started to occur.

Is there a fix for this other than reverting to ESX notifications? 

Example:
![image](https://user-images.githubusercontent.com/53144053/64236684-d73cbc00-cef2-11e9-90ca-deb2a65064df.png)

Thanks.

**Comment by Alzar** [comment]
This isn't doing anaything with GTA 5's UI rendering and is just sending a NUI message, would validate that anything dealing with however you were doing the alerts before are cleaned up
