### ISSUE TITLE
Make me a HTML UI mod that can take HTML from backend and display THANKS

### ISSUE THREAD

**Issue by DiscworldZA** [mythicrp/mythic_notify#3]

**Comment by Alzar** [comment]
As in for these notifications?

Inserting straight HTML into the text field [works](https://i.imgur.com/T6QbBOV.png), Code used;

```LUA
Citizen.CreateThread(function()
	while true do
		if IsControlJustReleased(0, 39) then
			SendAlert('error', '<span style="color: #fff000">FUCK U LUL</span>', 10000)
		end

		Citizen.Wait(1)
	end
end)
```

In reality, you can enter whatever you want for the type and it'll just apply that class which would have no styling unless you added it. Or you can add custom styling if you have a more recent version where [I had added that](https://github.com/mythicrp/mythic_notify/commit/991175e74f261e07e157377f5fa1d1ebeb39d288)

Feel free to hit me up on Discord if you wanna discuss it there ^^

**Comment by DiscworldZA** [comment]
Yeah the HTML does get passed but i want a full on UI mod. Kalbino said i should use NativeUI
